### ISSUE TITLE
[prettier-plugin-sql] Parser Options in README is out of date

### ISSUE THREAD

**Issue by frozenbonito** [un-ts/prettier#203]
[Parser Options](https://github.com/un-ts/prettier/blob/master/packages/sql/README.md#parser-options) does not seem to match the actual options.

https://github.com/un-ts/prettier/blob/7d4927582afc79dfb496926f7ddfb7ac1ff9c1e4/packages/sql/src/index.ts#L45-L370

**Comment by JounQin** [comment]
Thanks for reminding, and PR welcome! 👍
