### ISSUE TITLE
[prettier-plugin-sql] Option to insert final newline

### ISSUE THREAD

**Issue by frozenbonito** [un-ts/prettier#204]
`prettier-plugin-sql` formats files without final newline, but it conflicts with editorconfig etc.
It would be nice to have an option to insert a newline at the end of the file.

**Comment by JounQin** [comment]
That seems a very necessary feature, do you want to raise a PR for it? Or I can do it later when I'm free.

**Comment by frozenbonito** [comment]
Yes, I would like to work on it.

**Comment by JounQin** [comment]
> Yes, I would like to work on it.

That would be very nice.

In case you don't quite familiar with the code base, you can implement it at

https://github.com/un-ts/prettier/blob/7d4927582afc79dfb496926f7ddfb7ac1ff9c1e4/packages/sql/src/index.ts#L37-L43

**Comment by JounQin** [comment]
I'll hold on the release #206 for days, considering this new feature.
