### ISSUE TITLE
[prettier-plugin-sh]: TypeError [Error]: Cannot set property crypto of #<Object> which has only a getter

### ISSUE THREAD

**Issue by jlarmstrongiv** [un-ts/prettier#216]
Setting `NODE_OPTIONS="--experimental-global-webcrypto"` causes a crash:

```
TypeError [Error]: Cannot set property crypto of #<Object> which has only a getter
```

The [`--experimental-global-webcrypto`](https://nodejs.org/api/cli.html#--experimental-global-webcrypto) enables the [Web Crypto API](https://nodejs.org/api/webcrypto.html) from the [browser](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) in NodeJS as the global [crypto](https://developer.mozilla.org/en-US/docs/Web/API/crypto_property) property.

While I’ve disabled experimental NODE_OPTIONS while running prettier, this issue will likely occur in NodeJS v18.x, which become the LTS version in [October 2022](https://nodejs.org/en/about/releases/).

**Comment by jlarmstrongiv** [comment]
Occurs due to `node_modules/sh-syntax/lib/shim/js`:

```
import { randomFillSync } from 'node:crypto';
import _fs from 'node:fs';
import { performance } from 'node:perf_hooks';
globalThis.fs = _fs;
globalThis.crypto = {
    // @ts-expect-error
    getRandomValues: randomFillSync,
};
// @ts-expect-error
globalThis.performance = performance;
//# sourceMappingURL=shim.js.map
```

Specifically:

```
globalThis.crypto = {
    // @ts-expect-error
    getRandomValues: randomFillSync,
};
```

Perhaps a workaround would be:

```
if (!globalThis.crypto) {
    globalThis.crypto = {
        // @ts-expect-error
        getRandomValues: randomFillSync,
    };
}
```

**Comment by JounQin** [comment]
Would you like to raise a PR to `sh-syntax` instead?

**Comment by JounQin** [comment]
And also, please close issues on mvdan/sh and gopherjs, they're not related.

**Comment by jlarmstrongiv** [comment]
Sure!  Sorry about that.  Resolved in https://github.com/un-ts/sh-syntax/pull/52
