### ISSUE TITLE
prettier-plugin-sh fails when run from pre-commit. 

### ISSUE THREAD

**Issue by mikedlr** [un-ts/prettier#231]
When I run prettier-plugin-sh from pre-commit it fails with a message like the one below. 

    internal/modules/cjs/loader.js:638
        throw err;
        ^

    Error: Cannot find module 'node:path'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
      [... elided for brevity - see attached log ... ] 
        at Object.<anonymous> (/home/mikedlr/.cache/pre-commit/repoggidmgun/node_env-system/lib/node_modules/prettier-plugin-sh/lib/index.cjs:3:12)
      [... elided for brevity - see attached log ... ] 
    internal/modules/cjs/loader.js:638
        throw err;
I have run prettier-plugin-sh with what I believe are the correct magic incantations

      - repo: https://github.com/pre-commit/mirrors-prettier
        rev: "v3.0.0-alpha.0" # Use the sha / tag you want to point at
        hooks:
          - id: prettier
            additional_dependencies:
              - prettier@2.1.2
              - "@prettier/plugin-xml@0.12.0"
              - "prettier-plugin-sh@0.12.8"
              - "prettier-plugin-java@1.6.2"

**Comment by mikedlr** [comment]
**what I did** 

run `pre-commit run -a` 

**what happened**

pre-commit / prettier-plugin-sh failed with the mesage above as seen in the log attached #

[prettier-plugin-sh-fail.log](https://github.com/un-ts/prettier/files/9715291/prettier-plugin-sh-fail.log)
[pre-commit-config-yaml.txt](https://github.com/un-ts/prettier/files/9715303/pre-commit-config-yaml.txt)

**what I expected to happen**

prettier-plugin-sh would run and reformat my sell scripts.

**Comment by JounQin** [comment]
`Cannot find module 'node:path'` means you're using unsupported Node version.

**Comment by mikedlr** [comment]
shouldn't prettier be automatically upgrading to a supported one?

**Comment by JounQin** [comment]
> shouldn't prettier be automatically upgrading to a supported one?

No idea what you mean, prettier-plugin-sh requires `"node": "^12.20.0 || ^14.18.0 || >=16.0.0"`.

**Comment by JounQin** [comment]
You can use `v0.11` for now.
