### ISSUE TITLE
[prettier-plugin-sql] Adds extra space and beginning of files

### ISSUE THREAD

**Issue by ewhauser** [un-ts/prettier#237]
Test file:

```sql
 -- migrate:up
 create table users (
   id integer,
   name varchar(255)
 );
 insert into users (id, name) values (1, 'alice');

 -- migrate:down
 drop table users;
```

```shell
$ npm install prettier
$ npm install prettier-sql-format
$ prettier migration.sql # Note leading space in first line
 -- migrate:up
create table
  users (id integer, name varchar(255));

insert into
  users (id, name)
values
  (1, 'alice');

-- migrate:down
drop table
$ sql-formatter migration.sql # No leading space in first line
-- migrate:up
create table
  users (id integer, name varchar(255));

insert into
  users (id, name)
values
  (1, 'alice');

-- migrate:down
drop table
  users;
```

**Comment by JounQin** [comment]
Can you provide a runnable reproduction first?

**Comment by JounQin** [comment]
Interesting, so where is the leading space coming from? `sql-formatter` seems working fine as you tested.

**Comment by ewhauser** [comment]
I'm not sure. However, I thought the fix was reasonable given there is never a reason to have leading or trailing whitespace in a query.

**Comment by justinleebehnke** [comment]
The sql-formatter fixed this issue as of version 11.0.2.

Is it simply that this project is using an earlier version?

**Comment by ewhauser** [comment]
The latest version did fix it. I pushed an updated PR: https://github.com/un-ts/prettier/pull/238

**Comment by justinleebehnke** [comment]
@ewhauser thank you so much, just to clarify for @JounQin 

PR: #238 is now closed

PR: #246 is the fix
