### ISSUE TITLE
`prettier-plugin-sh`: not working for dotfiles?

### ISSUE THREAD

**Issue by krystof-k** [un-ts/prettier#249]
I'm getting:

```
.env.development.local[error] No parser could be inferred for file: .env.development.local
```

Just `.env` works fine.

**Comment by n1kk** [comment]
Same here

**Comment by n1kk** [comment]
Here's a workaround for now:
```js
// prettier.config.json
{
  "overrides": [
    {
      "files": [".env", ".env.*"],
      "options": {
        "parser": "sh"
      }
    }
  ]
}
```

**Comment by JounQin** [comment]
That's how prettier works.

**Comment by krystof-k** [comment]
@JounQin should I open the issue in Prettier repo then? It is definitely a bug, otherwise [this](https://github.com/un-ts/prettier/blob/master/scripts/languages.ts#L27) would work:

https://github.com/un-ts/prettier/blob/1fe239bdc0cee97a5c3be760cd5d9d7fb51e1fed/scripts/languages.ts#L27

**Comment by JounQin** [comment]
@krystof-k Hah, perhaps `.env.*` can not match `.env.development.local`, maybe we should add `.env.*.*` at the time. Can you change your local `node_modules` to test?

**Comment by krystof-k** [comment]
No, I think that's not it, just `.env.development` is not working either. I tried changing it locally, but I guess it wasn't working for me.
