### ISSUE TITLE
`prettier-plugin-sh`: using plugin with pnpm

### ISSUE THREAD

**Issue by n1kk** [un-ts/prettier#250]
Just want to leave this here for info, could help others.

If you use `pnpm` and you keep your prettier config in external sharable package, then you can run into an issue that prettier does not load plugin in your project where you consume your config. This is due to the fact that `pnpm` does not hoist modules to the root `node_modules` directory like other package managers, so prettier can't find them. 

The workaround is to manually resolve plugins in a `js` prettier config:
```js
module.exports = {
    plugins: [require.resolve("prettier-plugin-sh")],
};
```

Maybe it's worth mentioning it in docs?

**Comment by JounQin** [comment]
PR welcome.
