### ISSUE TITLE
`prettier-plugin-sql` uppercase broken

### ISSUE THREAD

**Issue by JoernBerkefeld** [un-ts/prettier#254]
I'm running prettier on SQL files and in the past that would have nicely uppercased the query as well. at some point that stopped working though.
My config:
![image](https://user-images.githubusercontent.com/1917227/214331229-aa26a89e-5c35-406e-a0d0-06ae89b27ee8.png)

test-sql:
```sql
Select
    f.Id as ContactId,
    f.EndDate,
    f.StartDate,
    SecondReminder,
    f.Enabled,
    f.CustomerSegment
from
    test f
    inner join test2 s on f.Seller = s.Seller

```

the above is one out of many I tried - haven't seen it working anywhere.

i tried playing with the uppercase value, setting it as a string for instance, but that lead to an error.

**Comment by JounQin** [comment]
Did you tried `keywordCase: 'upper'`?

**Comment by JoernBerkefeld** [comment]
thanks for letting me know, @JounQin

I do appreciate all your work here! 

Small ask though: Could you please include changes like this one in the [CHANGELOG.md](https://github.com/un-ts/prettier/blob/master/packages/sql/CHANGELOG.md) going forward? 

I looked at the [README.md history](https://github.com/un-ts/prettier/commits/master/packages/sql/README.md) to understand when this was changed and based on that history you must have updated that on or before July 21, 2022. That date matches release 0.10.0.

With this being a breaking change, I would have hoped to see a major version increase (see [semver](https://semver.org/)), but at the very least, I would assume that this is mentioned in the changelog.

I'm sure I'm not the only one that has your package as a dependency and I tend to rely on changelogs and type of version changes to understand if I need to take a closer look or can just upgrade. With neither happening, it makes it very difficult to work with it :(

**Comment by JounQin** [comment]
The package follows semver but it is still 0.x, so 0.9 -> 0.10 means breaking changes.

Since we're using sql-formatter inside, so I think maybe it would be worth to mention its breaking change in CHANGELOG of course, sorry I didn't do it before.

**Comment by JoernBerkefeld** [comment]
Thank you!

I did skim through the semver definition but couldn't directly find what you are stating - it does however say that 0.x is unstable at all times which I suppose is what you refer to. They recommend moving to 1.0 as soon as it's used in production.

Well - it IS used in production ;-) time to stand behind your product. it's doing a good job for the users of  https://www.npmjs.com/package/mcdev / https://github.com/Accenture/sfmc-devtools and I'm sure for many more out there

**Comment by JoernBerkefeld** [comment]
oh and - can confirm it's working like a charm. will include the change in my next release. thanks again for solving this for me

**Comment by bokub** [comment]
For anyone like me struggling to understand how to change the plugin options:

```js
export default {
  plugins: ['prettier-plugin-sql'],
  overrides: [
    {
      files: '*.sql',
      options: {
        keywordCase: 'upper', // <= here
      },
    },
  ],
};
```
