### ISSUE TITLE
[prettier-plugin-sql] Incorrect use of MIT license when depending on a GPL-licensed library

### ISSUE THREAD

**Issue by nene** [un-ts/prettier#255]
The [node-sql-parser](https://github.com/taozhi8833998/node-sql-parser) library (used by prettier-plugin-sql) is licensed under GPLv2.

The `prettier-plugin-sql` plugin uses this library, but is not licensed under GPLv2 or later as the GPL license requires. Instead it uses the permissive MIT license.

I assume that this is not intentional, but simply an oversight by the author, as JavaScript libraries nowadays seem to mostly come with very permissive licenses.

Suggested fix:

- Change the license of prettier-plugin-sql to GPLv2

**Comment by JounQin** [comment]
Thanks for notification, just align the LICENSE.
