### ISSUE TITLE
Cannot pass paramTypes options

### ISSUE THREAD

**Issue by rdsedmundo** [un-ts/prettier#261]
.prettierrc
```
  "overrides": [
    {
      "files": "*.sql",
      "options": {
          "numbered": [
            "$"
          ],
          "named": [
            ":"
          ]
        }
      }
    }
  ]
```

This throws:
> [error] Invalid paramTypes value. Expected , but received { numbered: ["$"], named: [":"] }.

A quick look in the [source code of the lib](https://github.com/ikatyang/vnopts#choiceschema) that Prettier uses, suggests that `value: Object` [as declared here](https://github.com/un-ts/prettier/blob/master/packages/sql/src/index.ts#L302) may not be a valid option.

**Comment by JounQin** [comment]
Duplicate of #233
