### ISSUE TITLE
[prettier-plugin-sh] sh extension not resolving

### ISSUE THREAD

**Issue by devcrev** [un-ts/prettier#273]
Since I updated to `prettier@3.0.0` and `prettier-plugin-sh@0.13.0` this command no longer reports `.sh` files that need formatting:

`prettier --check .`

With `prettier@2.8.8` and `prettier-plugin-sh@0.12.8` the above command would find `.sh` files that need formatting.

Please note with the aforementioned newer versions this wildcard pattern does work:

`prettier --check ./*.sh`

Here is my `.prettierrc.json`:
```
{
  "plugins": ["prettier-plugin-sh"]
}
```

**Comment by JounQin** [comment]
Any useful error message?

**Comment by devcrev** [comment]
No errors. Just acts as if there were no sh files needing a format when in
fact there are. Other file types recognized by prettier and need formatting
are listed.

**Comment by JounQin** [comment]
Can you please provide a runnable reproduction?

**Comment by devcrev** [comment]
Here you go. Both repos have the same files that need to be formatted.

[Repo for old](https://github.com/devcrev/p-sh-old)
```
$ npm run format

> p-sh-old@1.0.0 format
> prettier --check .

Checking formatting...
[warn] level-0/go.sh
[warn] level-0/hello.sh
[warn] level-0/level-1/another.sh
[warn] level-0/level-1/library.js
[warn] level-0/level-1/runme.sh
[warn] level-0/program.js
[warn] Code style issues found in 6 files. Forgot to run Prettier?
```

[Repo for new](https://github.com/devcrev/p-sh-new)
```
$ npm run format

> p-sh-new@1.0.0 format
> prettier --check .

Checking formatting...
[warn] level-0/level-1/library.js
[warn] level-0/program.js
[warn] Code style issues found in 2 files. Run Prettier to fix.
```

**Comment by JounQin** [comment]
close in favor of https://github.com/prettier/prettier/issues/15079
