### ISSUE TITLE
Unable to format SQL: Error: Parse error: Unexpected "{env}_s3_d" 

### ISSUE THREAD

**Issue by chriskathumbi** [un-ts/prettier#277]
Unable to format SQL: Error: Parse error: Unexpected "{env}_s3_datalake.{".
This is for parameterized SQL to query multiple tables like: 
 `SELECT 
     *,
     current_date - interval {interval} {period}
  FROM {database_name}.{table_name}`

It seems to fail due to the use of  `'{' , '}'`
Using ``` ' ` ' ``` doesn't help due to some dialects not supporting it
Is it possible to add char ignore or add a custom sql dialect for this sort of query?

**Comment by JounQin** [comment]
Please provide a runnable reproduction like GitHub repo.

**Comment by JounQin** [comment]
This should be reported to https://github.com/sql-formatter-org/sql-formatter instead.

cc @nene

---

https://github.com/un-ts/prettier/blob/a8a0ff495b4984928e69f317616196fc21808f2f/packages/sql/package.json#L48

And it seems we are outdated now, `sql-formatter` v13 has been released, PR welcome to upgrade it and test your failing case.

**Comment by nene** [comment]
Templating is not directly supported in SQL Formatter, [a workaround is to use paramTypes config option.](https://github.com/sql-formatter-org/sql-formatter#my-sql-contains-templating-syntax-which-sql-formatter-fails-to-parse)
