### ISSUE TITLE
[prettier-plugin-sql] enable SQLite

### ISSUE THREAD

**Issue by jlarmstrongiv** [un-ts/prettier#298]
Hi again 👋 hope you’re doing well!  Just thought I’d try `prettier-plugin-sql` and contribute a quick fix

According to the [npm package](https://www.npmjs.com/package/prettier-plugin-sql) and [README](https://github.com/un-ts/prettier/tree/master/packages/sql), the `prettier-plugin-sql` plugin supports `sqlite`.  

However, the `sqlite` option is not enabled https://github.com/un-ts/prettier/blob/master/packages/sql/src/index.ts#L87

PR incoming…

**Comment by JounQin** [comment]
Nice catch, it has been released. Thanks @jlarmstrongiv
