### ISSUE TITLE
`[error] Couldn't resolve parser "sh".` when upgrading to Prettier 3.1.0

### ISSUE THREAD

**Issue by nbouvrette** [un-ts/prettier#310]
I just upgraded to Prettier `3.1.0` this morning and got this new error:

`[error] Couldn't resolve parser "sh".`

When I downgrade to Prettier `3.0.3` the problem dissapears.

How to reproduce:

1) Clone `https://github.com/Avansai/next-multilingual`
2) Edit `packages.json` and set Prettier to version `3.1.0`
3) run `npm install`
4) run `npm test`

**Comment by JounQin** [comment]
<img width="886" alt="image" src="https://github.com/un-ts/prettier/assets/8336744/73f40f9d-720b-4628-83f9-a01aaf271dc2">

Seems like a `prettier` core bug?

cc @fisker @sosukesuzuki

**Comment by fisker** [comment]
I'll take a look.

**Comment by fisker** [comment]
Not bug. Missed `plugins` https://github.com/Avansai/next-multilingual/blob/main/example/.prettierrc.yaml

**Comment by fisker** [comment]
```
$ npx prettier --find-config-pah h example/.env.development
example/.prettierrc.yaml
```

**Comment by JounQin** [comment]
> I just upgraded to Prettier 3.1.0 this morning and got this new error:

> When I downgrade to Prettier 3.0.3 the problem dissapears.

@fisker But it seems a regression, what means config resolution changed.

**Comment by fisker** [comment]
Maybe a bug was fixed accidentally.

**Comment by fisker** [comment]
Oh, caused by https://github.com/prettier/prettier/pull/15433, in pre-v3.1 we doesn't format that file at all.

https://github.com/Avansai/next-multilingual/blob/c48503df8062304e215919a9ea2f04476d9b253a/package.json#L109C18-L109C36

**Comment by fisker** [comment]
And that's a bug you rasied..  https://github.com/prettier/prettier/issues/15079 😄

**Comment by JounQin** [comment]
OK, last thing is that the error message is a bit confusing? It successfully understands that it should use `sh` as the parser what means `prettier-plugin-sh` is already loaded correctly.

**Comment by fisker** [comment]
No, the plugin is not loaded, the config file tells prettier to use that parser, https://github.com/Avansai/next-multilingual/blob/c48503df8062304e215919a9ea2f04476d9b253a/example/.prettierrc.yaml#L25

**Comment by JounQin** [comment]
Hah, that makes sense then! Thanks for your explanation! Close due to answered as above then.

**Comment by nbouvrette** [comment]
Thanks @fisker and @JounQin - I'm not sure why it was working before?

I thought there was some sort of inheritance but maybe this is gone? in any case adding the `plugins` section in the `example` prettier config seems to solve the issue.

**Comment by JounQin** [comment]
> I'm not sure why it was working before?

> Oh, caused by https://github.com/prettier/prettier/pull/15433, in pre-v3.1 we doesn't format that file at all.

Please read the conversation carefully.

**Comment by nbouvrette** [comment]
I think I get it - thanks for looking into this!
