### ISSUE TITLE
[prettier-plugin-sql] export supported sql dialect names

### ISSUE THREAD

**Issue by Sec-ant** [un-ts/prettier#311]
Hi @JounQin 

Thanks for your work. I'm the author of [`prettier-plugin-embed`](https://github.com/Sec-ant/prettier-plugin-embed). It's an embedded language formatting plugin designed for prettier v3. We currently use your `prettier-plugin-sql` to support embedded sql language formatting.

We noticed that the supported sql dialects may differ across different versions of your plugin, so we were wondering if you could export the supported sql dialect names in the future versions? We depend on these names in our plugin to apply default values and auto select formatters: https://github.com/Sec-ant/prettier-plugin-embed/pull/31/commits/582c9aac62d3d5f1f875313dcbdf03e85cdf8482

**Comment by Sec-ant** [comment]
Here is one possible way to address our concern without needing to many changes or dev burden, if it is acceptable to you.

```diff
diff --git a/packages/sql/src/index.ts b/packages/sql/src/index.ts
index 81ceb70..84511b4 100644
--- a/packages/sql/src/index.ts
+++ b/packages/sql/src/index.ts
@@ -5,6 +5,7 @@ import type { AST, Option } from 'node-sql-parser'
 import nodeSqlParser from 'node-sql-parser'
 import type { Options, ParserOptions, Plugin } from 'prettier'
 import { format, type FormatOptions } from 'sql-formatter'
+import type { ReadonlyDeep } from 'type-fest'
 
 import { languages } from './languages.js'
 
@@ -32,7 +33,7 @@ export type SqlOptions = ParserOptions<AST> & SqlBaseOptions
 
 export type SqlFormatOptions = Options & SqlBaseOptions
 
-const SqlPlugin: Plugin<AST | string> = {
+export const ReadonlySqlPlugin = {
   languages,
   parsers: {
     sql: {
@@ -413,6 +414,6 @@ const SqlPlugin: Plugin<AST | string> = {
       ],
     },
   },
-}
+} as const satisfies ReadonlyDeep<Plugin<AST | string>>
 
-export default SqlPlugin
+export default ReadonlySqlPlugin as unknown as Plugin<AST | string>
```

**Comment by JounQin** [comment]
I'll take a look soon.

**Comment by Sec-ant** [comment]
No longer needed, thanks for your work!

**Comment by JounQin** [comment]
https://github.com/Sec-ant/prettier-plugin-embed/blob/2c2efc50ba500189f809317dfc44bfee505411d8/src/embedded/sql/options.ts#L15-L46

I think this should reopen?

**Comment by Sec-ant** [comment]
I think I can just use several common names as the default identifiers: https://github.com/Sec-ant/prettier-plugin-embed/blob/2c2efc50ba500189f809317dfc44bfee505411d8/src/embedded/sql/options.ts#L69

And those export types are not actually used anywhere. I should update that part of the code.

**Comment by JounQin** [comment]
> And those export types are not actually used anywhere. I should update that part of the code.

Good to know.
