### ISSUE TITLE
prettier-plugin-sql: Update to sql-formatter@14?

### ISSUE THREAD

**Issue by karlhorky** [un-ts/prettier#313]
Hi @JounQin, hope you're well! 👋

I saw that there was a new version [`sql-formatter@14.0.0`](https://github.com/sql-formatter-org/sql-formatter/releases/tag/v14.0.0), which introduces [a new `identifierCase` option](https://github.com/sql-formatter-org/sql-formatter/pull/663)

2 breaking changes, apparently removal of options which were already deprecated and broken:

> Breaking changes
>
> These already deprecated features were fundamentally broken and have been removed for good:
>
> - Removed tabulateAlias config option.
> - Removed commaPosition config option.

What do you think about upgrading to this new major version?

**Comment by JounQin** [comment]
PR welcome.

**Comment by karlhorky** [comment]
Ok, PR open at:

- https://github.com/un-ts/prettier/pull/315
