### ISSUE TITLE
prettier-plugin-sql: Allow `dialect` as alternative to `language`

### ISSUE THREAD

**Issue by karlhorky** [un-ts/prettier#322]
Hi @JounQin, hope you're good! 👋 

[`sql-formatter`](https://github.com/sql-formatter-org/sql-formatter) has an option called [`dialect`](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/dialect.md), which since v12 is a superior version of the [`language`](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/language.md) option, allowing also for [custom dialects](https://github.com/sql-formatter-org/sql-formatter/issues/156#issuecomment-1837192552).

This would mean also switching between the `format()` function and the new `formatDialect()` function when the `dialect` option is passed (also in the `dialect` docs above).

**Comment by JounQin** [comment]
This can be supported like #301 due to prettier's limitation, see also https://github.com/prettier/prettier/issues/14671

`language` and `dialect` should be supported at the same time.

PR welcome, or I can do it myself.

**Comment by JounQin** [comment]
By the way, can you help to finish #217 first?

**Comment by karlhorky** [comment]
> By the way, can you help to finish #217 first?

Will do, I'll be able to check out adding the docs for `prettier-plugin-sql` + `prettier-plugin-embed` to both projects in the next days.

**Comment by karlhorky** [comment]
@JounQin I found some time to do this:

- #334

**Comment by karlhorky** [comment]
I can confirm the `dialect` option is working in [`prettier-plugin-sql@0.18.0`](https://github.com/un-ts/prettier/releases/tag/prettier-plugin-sql%400.18.0) 🎉 Thanks for the release.
