### ISSUE TITLE
Possibility of updating the license again?

### ISSUE THREAD

**Issue by jayrave** [un-ts/prettier#323]
As part of https://github.com/un-ts/prettier/issues/255, the license of `prettier-plugin-sql` was updated from MIT to GPLv2 to be complaint with the license of one its dependencies - [node-sql-parser](https://github.com/taozhi8833998/node-sql-parser). Since then, that dependency [has been updated](https://github.com/taozhi8833998/node-sql-parser/issues/1481) to use Apache 2.0 starting from `v4.8`. As the version of that dependency this library uses is already `^4.11.0`, it should be possible to go back to MIT or use Apache 2.0 (since none of the other direct dependencies of this lib are GPL)

We would like to use this plugin in our codebase for formatting some SQL files & updating the license to be more permissive would make way for that. Happy to open a PR for that if it would help. Please let me know

**Comment by JounQin** [comment]
Sure, PR welcome.

**Comment by jayrave** [comment]
PR is up. Would you like for a changeset to also be added to the same PR?
