### ISSUE TITLE
[prettier-plugin-sh] Incorrectly splits RUN command

### ISSUE THREAD

**Issue by dbrugger** [un-ts/prettier#339]
Repro: https://github.com/dbrugger/prettier/blob/Dockerfile-cmd-split-repro/packages/sh/test/fixtures/run-semicolon.Dockerfile

Input:
```
RUN echo hi; echo hello
```

Output:

```
RUN echo hi
echo hello
```

Expected: keep as is

**Comment by dbrugger** [comment]
As workaround I added `Dockerfile` to `.prettierignore`. 
The case here is not very complex, and very standard. If the plugin does not intend to support such, would it not be better to disable that function by default in the plugin?

**Comment by dbrugger** [comment]
An important distinction also is:

1. Not supporting pretty formatting
2. Breaking the user's code

In this case it is (2).

**Comment by JounQin** [comment]
> If the plugin does not intend to support such, would it not be better to disable that function by default in the plugin?

I'm not certain actually, many users are just writing simple `Dockerfile` files as I described and they(including myself) want it can be enabled by default.

But it could be a good chance to add a related section describing the limitation.

**Comment by FelixZY** [comment]
@JounQin I had this issue in a dockerfile today:

```Dockerfile
FROM debian:bookworm
ENV ASPNETCORE_URLS http://+:5000;https://+:5001
```

is formatted as

```Dockerfile
FROM debian:bookworm
ENV ASPNETCORE_URLS http://+:5000
https://+:5001
```

I do not think I can add `\` as a workaround for this case.
