### ISSUE TITLE
prettier-plugin-sh: support .nvmrc files?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [un-ts/prettier#340]
Coming over here from https://github.com/prettier/prettier/issues/15898#issuecomment-1883395232: I'd like to use `prettier-plugin-sh` to format `.nvmrc` files. Given that the plugin supports similar files (`gitignore`, `dotenv`, ...), is this a reasonable use case for the plugin?

**Comment by JounQin** [comment]
Is there a `.nvmrc` spec?

**Comment by JoshuaKGoldberg** [comment]
I don't think there's a formal spec, no. Parsing of `.nvmrc` comes from commands in https://github.com/nvm-sh/nvm/blob/6c9cd2f2d1779b91c0ab7ab0b243c0c55f25a8a5/nvm.sh. Filed https://github.com/nvm-sh/nvm/issues/3265.

For now, `node -v` is the rough format it uses: `v`, a number, then 0-1 of `.` and more numbers.

* `v20`
* `v20.1`
* `v20.12`
* `v20.1.2`
* `v20.1.23`
* `v20.1.234`
* `v20.12.2`
* `v20.12.34`
* `v20.12.345`

Trailing whitespace and/or newlines seem to be fine as well.

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/c91ce25e556f67ea321cd0df260a08569e71d8f8/.nvmrc is an example of a working file.

```plaintext
20.11.0

```

**Comment by JoshuaKGoldberg** [comment]
Extra newlines after the version are allowed:

```plaintext
20.11.0


```

Playing around with it a bit more, it looks like whitespace on the same line are being parsed as the version number. So those can't be removed. But the following are ignored:

* Presence or lack of `v`
* Any text after a newline following the version number

So this is actually a totally valid `.nvmrc`:

```plaintext
20.11.0

...gotcha!
```

...now that I've played with this a bit more, maybe it deserves its own plugin?

**Comment by JoshuaKGoldberg** [comment]
Haha yeah it's just ignored. I've never seen it in the wild and didn't even think to try it out until after we started talking!

**Comment by JounQin** [comment]
If you only want to trim, I think maybe it could be added, with a reference doc. Would you like to raise a PR?
