### ISSUE TITLE
[warn] embeddedSqlIdentifiers is deprecated.

### ISSUE THREAD

**Issue by MrSwitch** [un-ts/prettier#348]
Getting the following 

> [warn] embeddedSqlIdentifiers is deprecated.

Is there another setting which should be used which isn't mentioned in the documentation?

Here's the `.prettierrc.js` file

```.prettierrc.js
const config = require('@5app/prettier-config');
config.plugins ??= [];
module.exports = {
    ...config,
    embeddedSqlIdentifiers: ['SQL'],
    plugins: [
        ...config.plugins,
        'prettier-plugin-embed',
        'prettier-plugin-sql'
    ],
}
```

Running Prettier@3.2.4

**Comment by JounQin** [comment]
I believe you mean

https://github.com/Sec-ant/prettier-plugin-embed?tab=readme-ov-file#embeddedsqlidentifiers
