### ISSUE TITLE
[prettier-plugin-sql] Broken indentation formatting in vscode

### ISSUE THREAD

**Issue by sequencerr** [un-ts/prettier#365]
npx prettier file gives normal result, but vscode, I guess extension gives incorrect result

formats like
```js
const newLocal = sql`
SELECT
	first_name,

	species

FROM

	animals

WHERE

	id = ${id}
`;
```

**Comment by sequencerr** [comment]
```js
endOfLine: 'crlf'
```
is cause

**Comment by LazyRichard** [comment]
I had same issue. so, I create PR for this https://github.com/un-ts/prettier/pull/358

**Comment by sequencerr** [comment]
@LazyRichard any updates from maintainers?
