### ISSUE TITLE
[prettier-plugin-sql] doesn't support esmodule out of box ?

### ISSUE THREAD

**Issue by zhangzhuang15** [un-ts/prettier#370]
I write a demo in `index.mjs`, which looks like:
```js 
const sourceCode = `
select * from s_table;select * from g_table;`

import * as prettier from "prettier"
import SqlPlugin from "prettier-plugin-sql";

let result = prettier.format(sourceCode, { plugins: [SqlPlugin], parser: 'sql'});

result.then(v => console.log(v))
```
then I execute `node index.mjs`, there is an error:
```
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/xxxxx/Project/prismjs-demo/node_modules/prettier-plugin-sql/lib/languages' imported from /Users/xxxxx/Project/prismjs-demo/node_modules/prettier-plugin-sql/lib/index.js
```

Are you going to support esmodule out of box ?

**Comment by JounQin** [comment]
<img width="437" alt="image" src="https://github.com/un-ts/prettier/assets/8336744/363ede71-b557-49bb-a14c-505b75f4425f">

I cannot reproduce it, it likes you're using an old version of `prettier-plugin-sql`.

**Comment by zhangzhuang15** [comment]
OK,I will check it later.



发自我的iPhone


------------------ Original ------------------
From: JounQin ***@***.***&gt;
Date: Wed,Jun 12,2024 9:29 PM
To: un-ts/prettier ***@***.***&gt;
Cc: JasonZhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [un-ts/prettier] [prettier-plugin-sql] doesn't support esmoduleout of box ? (Issue #370)

**Comment by zhangzhuang15** [comment]
> <img alt="image" width="437" src="https://private-user-images.githubusercontent.com/8336744/338986209-363ede71-b557-49bb-a14c-505b75f4425f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQ4NzgsIm5iZiI6MTcxODI0NDU3OCwicGF0aCI6Ii84MzM2NzQ0LzMzODk4NjIwOS0zNjNlZGU3MS1iNTU3LTQ5YmItYTE0Yy01MDViNzVmNDQyNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDIwOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGI4MzVhNTMyZjM5Y2E2YzE2YWVjZTgzNDczOWI3NjdiYzZjNDQ3NWY2MWNhNTFlMjI5MGY4NmNhNzZmNTMwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5OmA7V6gna7lqIimGScoifyZE5gHKiCinCp3UiagMos">
> I cannot reproduce it, it likes you're using an old version of `prettier-plugin-sql`.

You're right, my local version of this plugin is 0.4.1, I'll try new version instead,  thanks.
